### ISSUE TITLE
Play loop has the terrain tiny

### ISSUE THREAD

**Issue by kevin-b-lockwood** [intrvirate/NDCAYF#8]
![image](https://user-images.githubusercontent.com/57274670/92179474-932c1200-edf9-11ea-98e7-2c8ac007db40.png)
pretty obvious here. Just mostly documenting it here so we don't forget it

**Comment by kevin-b-lockwood** [comment]
Used old models presumably, when made clean the issue disappeared.

**Comment by kevin-b-lockwood** [comment]
sike, it's still here, it's just intermittent

**Comment by intrvirate** [comment]
Issue fixed; Bullet's model matrix doesn't store scale internally, it must be applied manually.
